;File will be downloaded to this directory.
FILE_PATH=D:\yt-dlp\out
;Name of the downloaded file. Set to "title_of_video.extension" by default.
;See https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template for a list of supported format strings.
FILE_NAME=%(title)s.%(ext)s
;FFMPEG location
FFMPEG_PATH=C:\ffmpeg\bin\ffmpeg.exe
YTDLP_PATH=D:\yt-dlp\bin\yt-dlp.exe

# ====================== Youtube credentials ======================

# YouTube credentials cookies will be read from this browser.
# NOTE: It is necessary to be logged in to YouTube in your browser before running the script.
# Currently supported browsers: brave, chrome, chromium, edge, firefox, opera, safari, vivaldi, whale
COOKIES_FROM_BROWSER=firefox
