;File will be downloaded to this directory.
FILE_PATH=C:\yt-dlp\out
;Name of the downloaded file. Set to "title_of_video.extension" by default.
;See https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template for a list of supported format strings.
FILE_NAME=%(title)s.%(ext)s
;FFMPEG location
FFMPEG_PATH=C:\ffmpeg\bin\ffmpeg.exe
YTDLP_PATH=C:\yt-dlp\bin\yt-dlp.exe